apiVersion: v1
kind: Service
metadata:
  name: alert-genie
  namespace: monitoring
  labels:
    app: alert-genie
spec:
  selector:
    app: alert-genie
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  type: ClusterIP
